services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: robot-game
    ports:
      - "4567:80"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - VITE_API_BACKEND_URL=
      - VITE_API_BASE_URL=https://websocket.iot.npic.edu.kh/api/v1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  app-network:
    driver: bridge
